version: '3'
services:

  db:
    container_name: mobydq-db
    restart: always
    image: mobydq-db
    build:
      context: ./db
    volumes:
      - mobydq-db-volume:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default

  graphql:
    container_name: mobydq-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env
    ports:
      - 5433:5433
    depends_on:
      - db
    links:
      - db
    networks:
      - default
    command: ["postgraphile", "--cors", "--connection", "${DATABASE_URL}", "--host", "0.0.0.0", "--port", "5433", "--schema", "base"]

  api:
    container_name: mobydq-api
    # restart: always
    image: mobydq-api
    build:
      context: ./api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_APP: api.py
      FLASK_RUN_PORT: 5434
    ports:
      - 5434:5434
    depends_on:
      - graphql
    links:
      - graphql
    networks:
      - default
    command: ["flask", "run", "--host=0.0.0.0"]

  scripts:
    container_name: mobydq-scripts
    restart: always
    image: mobydq-scripts
    build:
      context: ./scripts
      args:
        - GRAPHQL_URL=${GRAPHQL_URL}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_SENDER=${MAIL_SENDER}
    env_file:
      - ./.env
    depends_on:
      - graphql
    links:
      - graphql
    networks:
      - default

  app:
    container_name: mobydq-app
    restart: always
    image: mobydq-app
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - './app:/usr/src/app'
      - '/usr/src/app/node_modules'
    env_file:
      - ./.env
    ports:
      - 80:3000
    depends_on:
      - api
      - graphql
    links:
      - api
      - graphql
    networks:
      - default

networks:
  default:
    external:
      name: mobydq-network

volumes:
  mobydq-db-volume:
    external: true
