version: '3'
services:


  db:
    ports:
      - 5432:5432

  graphql:
    ports:
      - 5433:5433

  api:
    volumes:
      - ./api/init:/srv/api/
    environment:
      FLASK_DEBUG: 1

  scripts:
    volumes:
       - ./scripts/init:/srv/scripts
    tty: true

  app:
    image: mobydq-app-dev
    build:
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/usr/src/app
    expose:
      - 5499
    ports:
      - 5499:3000
